--delete com condição
DELETE FROM CLIENTE WHERE COD_CLIENTE = 1;
DELETE FROM LOCACOES WHERE COD_LOCACAO = 1; 

--delete todos os registros
DELETE FROM CARROS;
DELETE FROM MODELOS;
DELETE FROM MARCAS;
