--TRIGGER CASO O CLIENTE SELECIONADO PARA LOCACAO NAO EXISTA NA TABELA DE CLIENTES
CREATE TRIGGER TRG_LOCACOES_ADD 
	ON LOCACOES
	AFTER INSERT
	AS 
	IF NOT EXISTS (SELECT 0 FROM inserted REGISTRO
	INNER JOIN CLIENTES ON REGISTRO.COD_CLIENTE = CLIENTES.COD_CLIENTE)
	BEGIN
		THROW 51000, 'Cliente deve estar cadastrado na tabela CLIENTES', 1;   
	END


--STORED PROCEDURE PARA BUSCAR TODOS OS CLIENTES E FORMA DE CONTATO (NO CASO O EMAIL)
CREATE PROCEDURE SelecionarTodosContatos
AS
SELECT NOME,EMAIL FROM CLIENTES
GO;