INSERT INTO MARCAS (DESCRICAO) VALUES ('MITSUBISHI');

INSERT INTO MARCAS (DESCRICAO) VALUES ('FORD');

INSERT INTO MARCAS (DESCRICAO) VALUES ('TOYOTA');

INSERT INTO MARCAS (DESCRICAO) VALUES ('HONDA');

INSERT INTO MARCAS (DESCRICAO) VALUES ('BMW');

INSERT INTO MARCAS (DESCRICAO) VALUES ('PORSCHE');

INSERT INTO MARCAS (DESCRICAO) VALUES ('LAMBORGHINI');

INSERT INTO MARCAS (DESCRICAO) VALUES ('NISSAN');

