SELECT * FROM CARROS

SELECT * FROM CLIENTES

SELECT * FROM LOCACOES

SELECT * FROM MARCAS

SELECT * FROM MODELOS INNER JOIN MARCAS ON MODELOS.COD_MARCA = MARCAS.COD_MARCA WHERE MARCAS.COD_MARCA = 16

SELECT * FROM CARROS INNER JOIN MODELOS ON MODELOS.COD_MODELO = CARROS.COD_MODELO WHERE CARROS.COD_MODELO = 6