SELECT * FROM VEICULOS

SELECT * FROM CLIENTES

SELECT * FROM LOCACOES

SELECT * FROM MARCAS

SELECT * FROM MODELOS INNER JOIN MARCAS ON MODELOS.IdMarca = MARCAS.IdMarca WHERE MARCAS.IdMarca = 16

SELECT * FROM CARROS INNER JOIN MODELOS ON MODELOS.IdModelo = CARROS.IdModelo WHERE CARROS.IdModelo = 6