SELECT * FROM VEICULOS

SELECT * FROM CLIENTES

SELECT * FROM LOCACOES

SELECT * FROM MARCAS

SELECT * FROM MODELOS

--PRECISA DE 5 JOIN
SELECT * FROM MODELOS INNER JOIN MARCAS ON MODELOS.IdMarca = MARCAS.IdMarca WHERE MARCAS.IdMarca = 16

SELECT * FROM CARROS INNER JOIN MODELOS ON MODELOS.IdModelo = CARROS.IdModelo WHERE CARROS.IdModelo = 6

--SELECIONA O NOME DO CLIENTE E OS VALORES QUE ELE DEVE
SELECT CLIENTES.NOME,LOCACOES.VALOR FROM LOCACOES INNER JOIN CLIENTES ON CLIENTES.COD_CLIENTE = LOCACOES.COD_CLIENTE 

--SELECIONA O NOME DO CLIENTE E OS STATUS DE TODOS OS REGISTOS DE PAGAMENTO VINCULADOS A ELE
SELECT CLIENTES.NOME,PAGAMENTO.STATUSPAGAMENTO FROM PAGAMENTO INNER JOIN CLIENTES ON CLIENTES.COD_CLIENTE = PAGAMENTO.COD_CLIENTE 

--SELECIONA O NOME DO CLIENTE E AS FORMAS DE PAGAMENTO UTILIZADAS POR ELE
SELECT CLIENTES.NOME,PAGAMENTO.FORMAPAGAMENTO FROM PAGAMENTO INNER JOIN CLIENTES ON CLIENTES.COD_CLIENTE = PAGAMENTO.COD_CLIENTE 
