CREATE TABLE "MODELOS" (
	"IdModelo"	INTEGER NOT NULL,
	"IdMarca"	INTEGER NOT NULL,
	"Descricao"	TEXT NOT NULL CHECK(length("Descricao") <= 100),
	PRIMARY KEY("IdModelo" AUTOINCREMENT),
	FOREIGN KEY("IdMarca") REFERENCES "MARCAS"("IdMarca")
);