CREATE TABLE "MODELOS" (
	"COD_MODELO"	INTEGER NOT NULL,
	"COD_MARCA"	INTEGER NOT NULL,
	"DESCRICAO"	TEXT NOT NULL,
	PRIMARY KEY("COD_MODELO" AUTOINCREMENT),
	FOREIGN KEY("COD_MARCA") REFERENCES "MARCAS"("COD_MARCA")
);