CREATE TABLE "LOCACOES" (
	"COD_LOCACAO"	INTEGER NOT NULL,
	"COD_CARRO"	INTEGER NOT NULL,
	"COD_CLIENTE"	INTEGER NOT NULL,
	"DATA_RETIRADA"	TEXT NOT NULL,
	"DATA_DEVOLUCAO"	TEXT NOT NULL,
	"VALOR"	REAL NOT NULL,
	"OBSERVACAO"	TEXT,
	FOREIGN KEY("COD_CLIENTE") REFERENCES "CLIENTES"("COD_CLIENTE"),
	FOREIGN KEY("COD_CARRO") REFERENCES "CARROS"("COD_CARRO"),
	PRIMARY KEY("COD_LOCACAO" AUTOINCREMENT)
);