UPDATE CLIENTES SET EMAIL = 'TESTE@TESTE.COM' WHERE NOME = 'EU'
UPDATE CLIENTES SET SENHA = '456' WHERE NOME ='EU'

UPDATE CARROS SET COR = 'VERMELHO' WHERE COD_MODELO = 9
UPDATE CARROS SET COR = 'BRANCO' WHERE COD_MODELO = 4
UPDATE CARROS SET COR = 'PRETO' WHERE COD_MODELO = 3

